AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Dashboard for Gitea Infrastructure

Parameters:
  CustomIdentifier:
    Type: String
    Description: Unique identifier for resource naming.

Resources:
  GiteaDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub cmtr-${CustomIdentifier}-dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/RDS", "CPUUtilization", "DBInstanceIdentifier", "giteadb" ]
                ],
                "title": "RDS CPU Utilization",
                "period":300,
                "stat":"Average",
                "region":"us-east-1",
                "liveData": false,
                "legend": {
                    "position": "right"
              }
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/RDS", "DatabaseConnections", "DBInstanceIdentifier", "giteadb" ]
                ],
                "title": "RDS Connections",
                "period":300,
                "stat":"Average",
                "region":"us-east-1",
                "liveData": false,
                "legend": {
                    "position": "right"
                }
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ApplicationELB", "HealthyHostCount", "TargetGroup", "cmtr-${CustomIdentifier}-tg", "LoadBalancer", "$cmtr-${CustomIdentifier}-alb" ]
                ],
                "title": "ALB Healthy Hosts",
                "period":300,
                "stat":"Average",
                "region":"us-east-1",
                "liveData": false,
                "legend": {
                    "position": "right"
                }
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ApplicationELB", "RequestCount", "LoadBalancer", "$cmtr-${CustomIdentifier}-alb" ]
                ],
                "title": "ALB Request Count",
                "period":300,
                "stat":"Average",
                "region":"us-east-1",
                "liveData": false,
                "legend": {
                    "position": "right"
                }
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 12,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/EFS", "ClientConnections", "FileSystemId", "$cmtr-${CustomIdentifier}-efs" ]
                ],
                "title": "EFS Client Connections",
                "period":300,
                "stat":"Average",
                "region":"us-east-1",
                "liveData": false,
                "legend": {
                    "position": "right"
                }
              }
            }
          ]
        }

Outputs:
  DashboardName:
    Description: CloudWatch dashboard name
    Value: !Ref GiteaDashboard
    Export:
      Name: !Sub cmtr-${CustomIdentifier}-dashboard-name
