AWSTemplateFormatVersion: '2010-09-09'
Description: Creates IAM Role and Instance Profile for EC2 instances

Parameters:
  CustomIdentifier:
    Type: String
    Description: Unique identifier for resource naming.

Resources:
  GiteaInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub cmtr-${CustomIdentifier}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AdministratorAccess

  GiteaInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub cmtr-${CustomIdentifier}-profile
      Roles:
        - !Ref GiteaInstanceRole

Outputs:
  InstanceProfileName:
    Description: Name of the EC2 instance profile
    Value: !Ref GiteaInstanceProfile
    Export:
      Name: !Sub cmtr-${CustomIdentifier}-instance-profile
